// SugarCRM CE 6.1 SOAP API 2.1 Client Library
// Copyright (C) 2011  Antonio Musarra <antonio.musarra@gmail.com>
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shirus.crm.phpfogapp.com
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="sugarsoapBinding", Namespace="http://www.sugarcrm.com/sugarcrm")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(link_field))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(field))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(link_value2))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(link_name_value))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(link_list2))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(link_name_to_fields_array))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(name_value))]
    public partial class sugarsoap : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        
        /// <remarks/>
        public sugarsoap()
        {
            this.Url = "https://shirus-crm.phpfogapp.com/service/v2_1/soap.php";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/login", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public entry_value login(user_auth user_auth, string application_name, name_value[] name_value_list)
        {
            object[] results = this.Invoke("login", new object[] {
                        user_auth,
                        application_name,
                        name_value_list});
            return ((entry_value)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(user_auth user_auth, string application_name, name_value[] name_value_list, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("login", new object[] {
                        user_auth,
                        application_name,
                        name_value_list}, callback, asyncState);
        }
        
        /// <remarks/>
        public entry_value Endlogin(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((entry_value)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/logout", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        public void logout(string session)
        {
            this.Invoke("logout", new object[] {
                        session});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogout(string session, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("logout", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endlogout(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_entry", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public get_entry_result_version2 get_entry(string session, string module_name, string id, string[] select_fields, link_name_to_fields_array[] link_name_to_fields_array)
        {
            object[] results = this.Invoke("get_entry", new object[] {
                        session,
                        module_name,
                        id,
                        select_fields,
                        link_name_to_fields_array});
            return ((get_entry_result_version2)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_entry(string session, string module_name, string id, string[] select_fields, link_name_to_fields_array[] link_name_to_fields_array, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_entry", new object[] {
                        session,
                        module_name,
                        id,
                        select_fields,
                        link_name_to_fields_array}, callback, asyncState);
        }
        
        /// <remarks/>
        public get_entry_result_version2 Endget_entry(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((get_entry_result_version2)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_entries", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public get_entry_result_version2 get_entries(string session, string module_name, string[] ids, string[] select_fields, link_name_to_fields_array[] link_name_to_fields_array)
        {
            object[] results = this.Invoke("get_entries", new object[] {
                        session,
                        module_name,
                        ids,
                        select_fields,
                        link_name_to_fields_array});
            return ((get_entry_result_version2)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_entries(string session, string module_name, string[] ids, string[] select_fields, link_name_to_fields_array[] link_name_to_fields_array, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_entries", new object[] {
                        session,
                        module_name,
                        ids,
                        select_fields,
                        link_name_to_fields_array}, callback, asyncState);
        }
        
        /// <remarks/>
        public get_entry_result_version2 Endget_entries(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((get_entry_result_version2)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_entry_list", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public get_entry_list_result_version2 get_entry_list(string session, string module_name, string query, string order_by, int offset, string[] select_fields, link_name_to_fields_array[] link_name_to_fields_array, int max_results, int deleted)
        {
            object[] results = this.Invoke("get_entry_list", new object[] {
                        session,
                        module_name,
                        query,
                        order_by,
                        offset,
                        select_fields,
                        link_name_to_fields_array,
                        max_results,
                        deleted});
            return ((get_entry_list_result_version2)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_entry_list(string session, string module_name, string query, string order_by, int offset, string[] select_fields, link_name_to_fields_array[] link_name_to_fields_array, int max_results, int deleted, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_entry_list", new object[] {
                        session,
                        module_name,
                        query,
                        order_by,
                        offset,
                        select_fields,
                        link_name_to_fields_array,
                        max_results,
                        deleted}, callback, asyncState);
        }
        
        /// <remarks/>
        public get_entry_list_result_version2 Endget_entry_list(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((get_entry_list_result_version2)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/set_relationship", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_set_relationship_list_result set_relationship(string session, string module_name, string module_id, string link_field_name, string[] related_ids, name_value[] name_value_list, int delete)
        {
            object[] results = this.Invoke("set_relationship", new object[] {
                        session,
                        module_name,
                        module_id,
                        link_field_name,
                        related_ids,
                        name_value_list,
                        delete});
            return ((new_set_relationship_list_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginset_relationship(string session, string module_name, string module_id, string link_field_name, string[] related_ids, name_value[] name_value_list, int delete, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("set_relationship", new object[] {
                        session,
                        module_name,
                        module_id,
                        link_field_name,
                        related_ids,
                        name_value_list,
                        delete}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_set_relationship_list_result Endset_relationship(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_set_relationship_list_result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/set_relationships", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_set_relationship_list_result set_relationships(string session, string[] module_names, string[] module_ids, string[] link_field_names, string[][] related_ids, name_value[][] name_value_lists, int[] delete_array)
        {
            object[] results = this.Invoke("set_relationships", new object[] {
                        session,
                        module_names,
                        module_ids,
                        link_field_names,
                        related_ids,
                        name_value_lists,
                        delete_array});
            return ((new_set_relationship_list_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginset_relationships(string session, string[] module_names, string[] module_ids, string[] link_field_names, string[][] related_ids, name_value[][] name_value_lists, int[] delete_array, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("set_relationships", new object[] {
                        session,
                        module_names,
                        module_ids,
                        link_field_names,
                        related_ids,
                        name_value_lists,
                        delete_array}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_set_relationship_list_result Endset_relationships(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_set_relationship_list_result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_relationships", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public get_entry_result_version2 get_relationships(string session, string module_name, string module_id, string link_field_name, string related_module_query, string[] related_fields, link_name_to_fields_array[] related_module_link_name_to_fields_array, int deleted)
        {
            object[] results = this.Invoke("get_relationships", new object[] {
                        session,
                        module_name,
                        module_id,
                        link_field_name,
                        related_module_query,
                        related_fields,
                        related_module_link_name_to_fields_array,
                        deleted});
            return ((get_entry_result_version2)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_relationships(string session, string module_name, string module_id, string link_field_name, string related_module_query, string[] related_fields, link_name_to_fields_array[] related_module_link_name_to_fields_array, int deleted, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_relationships", new object[] {
                        session,
                        module_name,
                        module_id,
                        link_field_name,
                        related_module_query,
                        related_fields,
                        related_module_link_name_to_fields_array,
                        deleted}, callback, asyncState);
        }
        
        /// <remarks/>
        public get_entry_result_version2 Endget_relationships(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((get_entry_result_version2)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/set_entry", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_set_entry_result set_entry(string session, string module_name, name_value[] name_value_list)
        {
            object[] results = this.Invoke("set_entry", new object[] {
                        session,
                        module_name,
                        name_value_list});
            return ((new_set_entry_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginset_entry(string session, string module_name, name_value[] name_value_list, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("set_entry", new object[] {
                        session,
                        module_name,
                        name_value_list}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_set_entry_result Endset_entry(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_set_entry_result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/set_entries", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_set_entries_result set_entries(string session, string module_name, name_value[][] name_value_lists)
        {
            object[] results = this.Invoke("set_entries", new object[] {
                        session,
                        module_name,
                        name_value_lists});
            return ((new_set_entries_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginset_entries(string session, string module_name, name_value[][] name_value_lists, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("set_entries", new object[] {
                        session,
                        module_name,
                        name_value_lists}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_set_entries_result Endset_entries(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_set_entries_result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_server_info", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public get_server_info_result get_server_info()
        {
            object[] results = this.Invoke("get_server_info", new object[0]);
            return ((get_server_info_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_server_info(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_server_info", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public get_server_info_result Endget_server_info(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((get_server_info_result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_user_id", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string get_user_id(string session)
        {
            object[] results = this.Invoke("get_user_id", new object[] {
                        session});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_user_id(string session, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_user_id", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget_user_id(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_module_fields", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_module_fields get_module_fields(string session, string module_name, string[] fields)
        {
            object[] results = this.Invoke("get_module_fields", new object[] {
                        session,
                        module_name,
                        fields});
            return ((new_module_fields)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_module_fields(string session, string module_name, string[] fields, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_module_fields", new object[] {
                        session,
                        module_name,
                        fields}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_module_fields Endget_module_fields(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_module_fields)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/seamless_login", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int seamless_login(string session)
        {
            object[] results = this.Invoke("seamless_login", new object[] {
                        session});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginseamless_login(string session, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("seamless_login", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public int Endseamless_login(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/set_note_attachment", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_set_entry_result set_note_attachment(string session, new_note_attachment note)
        {
            object[] results = this.Invoke("set_note_attachment", new object[] {
                        session,
                        note});
            return ((new_set_entry_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginset_note_attachment(string session, new_note_attachment note, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("set_note_attachment", new object[] {
                        session,
                        note}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_set_entry_result Endset_note_attachment(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_set_entry_result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_note_attachment", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_return_note_attachment get_note_attachment(string session, string id)
        {
            object[] results = this.Invoke("get_note_attachment", new object[] {
                        session,
                        id});
            return ((new_return_note_attachment)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_note_attachment(string session, string id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_note_attachment", new object[] {
                        session,
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_return_note_attachment Endget_note_attachment(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_return_note_attachment)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/set_document_revision", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_set_entry_result set_document_revision(string session, document_revision note)
        {
            object[] results = this.Invoke("set_document_revision", new object[] {
                        session,
                        note});
            return ((new_set_entry_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginset_document_revision(string session, document_revision note, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("set_document_revision", new object[] {
                        session,
                        note}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_set_entry_result Endset_document_revision(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_set_entry_result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_document_revision", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public new_return_document_revision get_document_revision(string session, string i)
        {
            object[] results = this.Invoke("get_document_revision", new object[] {
                        session,
                        i});
            return ((new_return_document_revision)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_document_revision(string session, string i, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_document_revision", new object[] {
                        session,
                        i}, callback, asyncState);
        }
        
        /// <remarks/>
        public new_return_document_revision Endget_document_revision(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((new_return_document_revision)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/search_by_module", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public return_search_result search_by_module(string session, string search_string, string[] modules, int offset, int max_results)
        {
            object[] results = this.Invoke("search_by_module", new object[] {
                        session,
                        search_string,
                        modules,
                        offset,
                        max_results});
            return ((return_search_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsearch_by_module(string session, string search_string, string[] modules, int offset, int max_results, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("search_by_module", new object[] {
                        session,
                        search_string,
                        modules,
                        offset,
                        max_results}, callback, asyncState);
        }
        
        /// <remarks/>
        public return_search_result Endsearch_by_module(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((return_search_result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_available_modules", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public module_list get_available_modules(string session)
        {
            object[] results = this.Invoke("get_available_modules", new object[] {
                        session});
            return ((module_list)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_available_modules(string session, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_available_modules", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public module_list Endget_available_modules(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((module_list)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_user_team_id", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string get_user_team_id(string session)
        {
            object[] results = this.Invoke("get_user_team_id", new object[] {
                        session});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_user_team_id(string session, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_user_team_id", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget_user_team_id(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/set_campaign_merge", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        public void set_campaign_merge(string session, string[] targets, string campaign_id)
        {
            this.Invoke("set_campaign_merge", new object[] {
                        session,
                        targets,
                        campaign_id});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginset_campaign_merge(string session, string[] targets, string campaign_id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("set_campaign_merge", new object[] {
                        session,
                        targets,
                        campaign_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endset_campaign_merge(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://shirus-crm.phpfogapp.com/service/v2_1/soap.php/get_entries_count", RequestNamespace="http://www.sugarcrm.com/sugarcrm", ResponseNamespace="http://www.sugarcrm.com/sugarcrm")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public get_entries_count_result get_entries_count(string session, string module_name, string query, int deleted)
        {
            object[] results = this.Invoke("get_entries_count", new object[] {
                        session,
                        module_name,
                        query,
                        deleted});
            return ((get_entries_count_result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_entries_count(string session, string module_name, string query, int deleted, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_entries_count", new object[] {
                        session,
                        module_name,
                        query,
                        deleted}, callback, asyncState);
        }
        
        /// <remarks/>
        public get_entries_count_result Endget_entries_count(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((get_entries_count_result)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class user_auth
    {
        
        /// <remarks/>
        public string user_name;
        
        /// <remarks/>
        public string password;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class get_entries_count_result
    {
        
        /// <remarks/>
        public int result_count;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class module_list
    {
        
        /// <remarks/>
        public string[] modules;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class return_search_result
    {
        
        /// <remarks/>
        public link_name_value[] entry_list;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class link_name_value
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public link_value2[] records;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class link_value2
    {
        
        /// <remarks/>
        public name_value[] link_value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class name_value
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class new_return_document_revision
    {
        
        /// <remarks/>
        public document_revision document_revision;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class document_revision
    {
        
        /// <remarks/>
        public string id;
        
        /// <remarks/>
        public string document_name;
        
        /// <remarks/>
        public string revision;
        
        /// <remarks/>
        public string filename;
        
        /// <remarks/>
        public string file;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class new_return_note_attachment
    {
        
        /// <remarks/>
        public new_note_attachment note_attachment;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class new_note_attachment
    {
        
        /// <remarks/>
        public string id;
        
        /// <remarks/>
        public string filename;
        
        /// <remarks/>
        public string file;
        
        /// <remarks/>
        public string related_module_id;
        
        /// <remarks/>
        public string related_module_name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class link_field
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        public string relationship;
        
        /// <remarks/>
        public string module;
        
        /// <remarks/>
        public string bean_name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class field
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        public string label;
        
        /// <remarks/>
        public int required;
        
        /// <remarks/>
        public name_value[] options;
        
        /// <remarks/>
        public string default_value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class new_module_fields
    {
        
        /// <remarks/>
        public string module_name;
        
        /// <remarks/>
        public field[] module_fields;
        
        /// <remarks/>
        public link_field[] link_fields;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class get_server_info_result
    {
        
        /// <remarks/>
        public string flavor;
        
        /// <remarks/>
        public string version;
        
        /// <remarks/>
        public string gmt_time;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class new_set_entries_result
    {
        
        /// <remarks/>
        public string[] ids;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class new_set_entry_result
    {
        
        /// <remarks/>
        public string id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class new_set_relationship_list_result
    {
        
        /// <remarks/>
        public int created;
        
        /// <remarks/>
        public int failed;
        
        /// <remarks/>
        public int deleted;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class get_entry_list_result_version2
    {
        
        /// <remarks/>
        public int result_count;
        
        /// <remarks/>
        public int next_offset;
        
        /// <remarks/>
        public entry_value[] entry_list;
        
        /// <remarks/>
        public link_list2[] relationship_list;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class entry_value
    {
        
        /// <remarks/>
        public string id;
        
        /// <remarks/>
        public string module_name;
        
        /// <remarks/>
        public name_value[] name_value_list;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class link_list2
    {
        
        /// <remarks/>
        public link_name_value[] link_list;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class get_entry_result_version2
    {
        
        /// <remarks/>
        public entry_value[] entry_list;
        
        /// <remarks/>
        public link_list2[] relationship_list;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.1.0.8000-736b5b66")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.sugarcrm.com/sugarcrm")]
    public partial class link_name_to_fields_array
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string[] value;
    }
}
